### ISSUE TITLE
Create command line interface for generation of Photon File through Stage 1

### ISSUE THREAD

**Issue by bcarlborg** [mwisniewski0/Real-Time-Photon-Mapper#10]
create a command line interface for the stage 1 program.
- command line interface will allow for specification of input file
- command line interface will allow for degree of control over render time
- command line interface will display ascii progress bar in order to know how long you have to get coffee
- command line interface will allow for specification of the output photon file.

**Comment by mwisniewski0** [comment]
Currently, we resigned from the following goals:
* command line interface will allow for degree of control over render time
* command line interface will display ascii progress bar in order to know how long you have to get coffee

This issue should be reopened once photon tracing is at a stage at which we are able to use it correctly in stage 1.
