### ISSUE TITLE
Evaluate the viability of using Vulkan for stage 2 (real-time part) of the render

### ISSUE THREAD

**Issue by mwisniewski0** [mwisniewski0/Real-Time-Photon-Mapper#3]
We need to evaluate whether Vulkan is a viable tool for developing the stage 2 (real-time part) of the renderer. Some of the potential pros for this technology are:

- Maximum control over the hardware to maximize performance
- Better integration with hardware than OpenGL that enables us to get higher framerates
- Portability between all major platforms for Photon: Windows, Mac, Linux, iOS, Android

@samkottler Please edit this issue with findings.

**Comment by samkottler** [comment]
Vulkan is certainly correct tool for stage 2 as more control over the device will help us get usable framerates on lower powered machines. However, having that much control over the device is super complicated and it is not feasible for any of us to learn how to use Vulkan during the time frame we have. We should use OpenGL for now since Mike is already familiar with it and keep Vulkan in mind for a possible improvement down the line.
